# Generated by Django 5.2.8 on 2025-11-19 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, verbose_name='Адреса')),
                ('working_hours', models.CharField(max_length=100, verbose_name='Графік роботи')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Повідомлення')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.client', verbose_name='Клієнт')),
            ],
        ),
    ]
