# Generated by Django 5.2.8 on 2025-12-01 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_delivery_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='bonuses_used',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Використано бонусів'),
        ),
    ]
