# Generated by Django 5.2.8 on 2025-11-20 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='subscribers',
            field=models.ManyToManyField(blank=True, related_name='subscribed_products', to='users.client', verbose_name='Підписані клієнти'),
        ),
    ]
