# Generated by Django 5.2.8 on 2025-11-26 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_subscribers'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_social_program',
            field=models.BooleanField(default=False, verbose_name='Соціальна програма'),
        ),
    ]
