# Generated by Django 5.2.8 on 2025-11-19 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Тип (статус)')),
                ('discount_percent', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Знижка %')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Назва ролі')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('password_hash', models.CharField(max_length=255, verbose_name='Хеш пароля')),
                ('name', models.CharField(max_length=255, verbose_name='ПІБ')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('client_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.clienttype', verbose_name='Тип клієнта')),
                ('roles', models.ManyToManyField(to='users.role', verbose_name='Ролі')),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateField(verbose_name='Дата видачі')),
                ('file_path', models.CharField(max_length=500, verbose_name='Шлях до файлу')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='users.client', verbose_name='Клієнт')),
            ],
        ),
    ]
