# Generated by Django 5.2.8 on 2025-11-26 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='bonus_points',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Бонусні бали'),
        ),
    ]
