# Generated by Django 5.2.8 on 2025-11-30 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_is_social_program'),
        ('users', '0002_client_bonus_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='file_path',
        ),
        migrations.AddField(
            model_name='prescription',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Ліки'),
        ),
    ]
